export const speakers = [
    
   
{name: 'Aashish Sharma', designation: 'Vice President', company: 'Capgemini', image: require('./images/Aashish Sharma.png')},,,,
{name: 'Ajay Singh', designation: 'Senior Vice President and CEO - People Services', company: 'Quess Corp Limited', image: require('./images/Ajay Singh.png')},,,,
{name: 'Akanksha Shukla', designation: 'Assistant Vice President - Turnaround and Strategy', company: 'Edelweiss Financial Services', image: require('./images/Akanksha Shukla.png')},,,,
{name: 'Akshat Mohindra', designation: 'Global Account Manager', company: 'CISCO', image: require('./images/Akshat Mohindra.png')},,,,
{name: 'Aman Grover', designation: 'Head of App Dev Solutions', company: 'Google', image: require('./images/Aman Grover.png')},,,,
{name: 'Amit Tripathi', designation: 'Chief Executive Officer', company: 'Geolife Agritech India Private Limited', image: require('./images/Amit Tripathi.png')},,,,
{name: 'Amitabh Ray', designation: 'Managing Director', company: 'Ericsson India Global Services', image: require('./images/Amitabh Ray.png')},,,,
{name: 'Anjani B Kuumar', designation: 'HR Head', company: 'MX Player', image: require('./images/Anjani B Kuumar.png')},,,,
{name: 'Anuranjita Kumar', designation: 'Founder and CEO', company: 'Wit-ACE', image: require('./images/Anuranjita Kumar.png')},,,,
{name: 'Apurv Bhatnagar', designation: 'Head of Marketing', company: 'Incedo Inc', image: require('./images/Apurv Bhatnagar.png')},,,,
{name: 'Apurv Bhatnagar', designation: 'Head of Analyst Relations', company: 'AWS', image: require('./images/Apurv Bhatnagar.png')},,,,
{name: 'Avik Sarkar', designation: 'CMO, South Africa', company: 'Kellogg Company', image: require('./images/Avik Sarkar.png')},,,,
// {name: 'Debopriya Sengupta', designation: 'Director HR', company: 'Whirlpool', image: require('./images/Debopriya Sengupta.png')},,,,
{name: 'Dhananjay Yadav', designation: 'Associate VP', company: 'Homelane', image: require('./images/Dhananjay Yadav.png')},,,,
{name: 'Dola Halder', designation: 'Brand Manager', company: 'Pepsico India', image: require('./images/Dola Halder.png')},,,,
{name: 'Dr. Ankita Singh', designation: 'SVP and Global Head', company: 'Cignex Datamatics', image: require('./images/Dr. Ankita Singh.png')},,,,
{name: 'Dr. Sachin Gulati', designation: 'Global Campus Program Strategy', company: 'American Express', image: require('./images/Dr. Sachin Gulati.png')},,,,
{name: 'Govil Aggarwal', designation: 'Associate Director', company: 'Michael Page', image: require('./images/Govil Aggarwal.png')},,,,
{name: 'Ibotombi Longjam', designation: 'Director and Head , Model Risk Management India', company: 'CITI Group', image: require('./images/Ibotombi Longjam.png')},,,,
{name: 'Kaushik Mitra', designation: 'Vice President and CFO', company: 'PepsiCo India', image: require('./images/Kaushik Mitra.png')},,,,
{name: 'Michelle Thompson Dolberry', designation: 'Vice President - USA Global Inclusion and Diversity', company: 'American Express', image: require('./images/Michelle Thompson Dolberry.png')},,,,
{name: 'Nixon Joseph', designation: 'President and Chief Operating Officer', company: 'SBI Foundation', image: require('./images/Nixon Joseph.png')},,,,
{name: 'Pramath Malik', designation: 'Sales Director', company: 'Grid Dynamics', image: require('./images/Pramath Malik.png')},,,,
{name: 'Pratyush Singh', designation: 'Engagement Director', company: 'Salesforce', image: require('./images/Pratyush Singh.png')},,,,
{name: 'Rajesh Kumar', designation: 'Vice President, Marketing - India and South Asia', company: 'UiPath', image: require('./images/Rajesh Kumar.png')},,,,
// {name: 'Rajita Singh ', designation: 'Head HR', company: 'Broadridge Financial Solutions', image: require('./images/Rajita Singh .png')},,,,
{name: 'Rajiv Krishnan', designation: 'Managing Director', company: 'Kornferry India', image: require('./images/Rajiv Krishnan.png')},,,,
{name: 'Rakesh Mehta', designation: 'Senior Vice President', company: 'JSW Energy Limited', image: require('./images/Rakesh Mehta.png')},,,,
{name: 'Reena Bhansali', designation: 'VP - Human Resources', company: 'Matellio', image: require('./images/Reena Bhansali.png')},,,,
// {name: 'Rishu Garg', designation: 'CHRO', company: 'RIVIGO', image: require('./images/Rishu Garg.png')},,,,
{name: 'Runa Joshi', designation: 'Senior Director', company: 'Capgemini', image: require('./images/Runa Joshi.png')},,,,
{name: 'Satish Rajarathnam', designation: 'SVP and Global Head', company: 'Mphasis', image: require('./images/Satish Rajarathnam.png')},,,,
{name: 'Sharad Goel', designation: 'Director', company: 'Walmart Global Tech', image: require('./images/Sharad Goel.png')},,,,
{name: 'Shobhit Mohan', designation: 'Vice President - Marketing', company: 'PayU', image: require('./images/Shobhit Mohan.png')},,,,
{name: 'Sumit Jasoria', designation: 'Managing Director', company: 'Meero', image: require('./images/Sumit Jasoria.png')},,,,
// {name: 'Sumonta Mazumder', designation: 'AVP - Marketing Development', company: 'TATA Elxsi', image: require('./images/Sumonta Mazumder.png')},,,,
{name: 'Sundeep Reddy', designation: 'Head of Analytics and Hiring', company: 'Gramener', image: require('./images/Sundeep Reddy.png')},,,,
{name: 'Sushmita Roy', designation: 'SVP and Head HR', company: 'SET India', image: require('./images/Sushmita Roy.png')},,,,
{name: 'Swati Bhargava', designation: 'Co-Founder', company: 'Cash Karo & Earn Karo', image: require('./images/Swati Bhargava.png')},,,,
{name: 'Tarun Jha', designation: 'Head of Marketing', company: 'Skoda Auto', image: require('./images/Tarun Jha.png')},,,,
{name: 'Uzma Rushdi', designation: 'SVP - Strategic and Emerging Alliances', company: 'HDFC Life', image: require('./images/Uzma Rushdi.png')},,,,
{name: 'Varun Gupta', designation: 'Vice President - Strategy and Operations', company: 'Groww India', image: require('./images/Varun Gupta.png')},,,,
{name: 'Varun Sridhar', designation: 'CEO', company: 'Paytm Money', image: require('./images/Varun Sridhar.png')},,,,
{name: 'Vinay Trivedi', designation: 'CHRO', company: 'ToneTag', image: require('./images/Vinay Trivedi.png')},,,,
{name: 'Vishal Kapil', designation: 'CTO', company: 'Leading Fashion Retailer', image: require('./images/Vishal Kapil.png')},,,,
]
